version: "3.8"

services:
  example-cosmos:
    image: example-cosmos
    container_name: example-cosmos
    build:
      context: ./example/cosmos/chain
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"