version: "3.8"

services:
  example-cosmos:
    image: example-cosmos
    container_name: example-cosmos
    build:
      context: ./example/cosmos/chain
    ports:
      - 9099:9099
      - 9091:9091
      - 26657:26657